import React from 'react';
import {
  Btc,
  Eth,
  Ltc,
  Xrp,
  Xrp2,
  Bth,
  Xlm,
  Ada,
  Etc,
  Doge,
  Eos,
  Bnb,
  Xmr,
  Zec,
  USD,
  Trx,
  $Icon,
  SUM,
  RUB,
  SOM,
  KZT,
} from '../../Svg';
export default {
  BTC: {image: <Btc />},
  ETH: {image: <Eth />},
  LTC: {image: <Ltc />},
  BCH: {image: <Bth />},
  TRX: {image: <Trx />},
  ETC: {image: <Etc />},
  ZEC: {image: <Zec />},
  XMR: {image: <Xmr />},
  BNB: {image: <Bnb />},
  EOS: {image: <Eos />},
  XLM: {image: <Xlm />},
  ZIL: {image: <Xrp2 />},
  ADA: {image: <Ada />},
  DOGE: {image: <Doge />},
  USD: {image: <$Icon />},
  RUR: {image: <RUB />},
  USDTSUM: {image: <SUM />},
  USDTUSD: {image: <USD />},
  USDTRUB: {image: <RUB />},
  USDTKGS: {image: <SOM />},
  USDTKZT: {image: <KZT />},
};
